# Default values for tushare-integration.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: zhangbc/tushare-integration
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.1.0"

cronjob:
  - name: daily-morning
    cron_expr: "0 8 * * 1-5"
    spiders:
      - name: "stock/basic/stock_basic"
      - name: "stock/basic/stock_company"

  - name: daily-open
    cron_expr: "40 9 * * 1-5"
    spiders:
      - name: "stock/quotes/adj_factor"
      - name: "stock/quotes/stk_limit"
  - name: daily
    cron_expr: "0 16,17 * * 1-5"
    spiders:
      - name: "stock/quotes/daily"
      - name: "stock/quotes/suspend_d"
      - name: "stock/basic/namechange"
  - name: daily-evening
    cron_expr: "0 19 * * 1-5"
    spiders:
      - name: "stock/quotes/hsgt_top10"
      - name: "stock/quotes/moneyflow"
      - name: "stock/quotes/moneyflow_hsgt"
  - name: nightly
    cron_expr: "0 21 * * *"
    spiders:
      - name: "stock/quotes/stk_mins"
  - name: monthly
    cron_expr: "0 0 1 * *"
    spiders:
      - name: "stock/basic/trade_cal"
  - name: weekly
    cron_expr: "0 8 * * 1"
    spiders:
      - name: "stock/financial/balancesheet"
      - name: "stock/financial/cashflow"
      - name: "stock/financial/income"
      - name: "stock/financial/forecast"
      - name: "stock/financial/fina_indicator"
      - name: "stock/financial/fina_audit"
      - name: "stock/financial/fina_mainbz"
      - name: "stock/financial/express"
      - name: "stock/financial/dividend"
      - name: "stock/financial/disclosure_date"

configOverrides:
  # TUSHARE相关配置
  tushare_url: https://api.tushare.pro
  tushare_point: 5000
  tushare_token: ""

  database:
    # 数据库配置
    db_type: "clickhouse"
    host: "clickhouse"
    port: "8123"
    user: "default"
    password: ""
    db_name: "default"
    template_params: {}

  reporters:
    - "tushare_integration.reporters.FeishuWebHookReporter"

  # 飞书Webhook配置
  feishu_webhook: ""

  # 并行模式，当开启并行模式时，每个任务将会独立的创建一个CronJob，使用并行模式可以更为简单的查看任务的执行情况
  # 请注意，由于采集服务本身不是并行安全的，并行模式下需要人工处理好任务间的依赖问题，并且不支持使用正则表达式
  parallel_mode: true
  # Scrapy配置
  bot_name: tushare_integration
  concurrent_requests: 1
  concurrent_items: 100

  downloader_middlewares:
    scrapy.downloadermiddlewares.retry.RetryMiddleware: null
    tushare_integration.middlewares.TushareRetryDownloaderMiddleware: 543

  item_pipelines:
    tushare_integration.pipelines.TushareIntegrationFillNAPipeline: 298
    tushare_integration.pipelines.TransformDTypePipeline: 299
    tushare_integration.pipelines.TushareIntegrationDataPipeline: 300
    tushare_integration.pipelines.RecordLogPipeline: 301

  # 重试配置
  # Tushare的频次限制是一分钟为周期，重试只要大于这个周期理论上不会有任何问题
  retry_enabled: true
  retry_delay: 10
  retry_times: 6

  spider_modules:
    - "tushare_integration.spiders"

  closespider_errorcount: 1

nodeSelector: {}

tolerations: []

affinity: {}
