[tool.poetry]
name = "tushare-integration"
version = "0.1.0"
description = ""
authors = ["zhangbingchen <1731259685@qq.com>"]
readme = "README.md"
packages = [{ include = "tushare_integration" }]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
scrapy = "^2.11.0"
pyyaml = "^6.0.1"
typer = "^0.9.0"
rich = "^13.7.0"
pandas = "^2.2.0"
sqlalchemy = "^2.0.25"
jinja2 = "^3.1.3"
pydantic = "^2.5.3"
requests = "^2.31.0"
clickhouse-connect = "^0.7.0"
pydantic-settings = "^2.1.0"

[tool.black]
line-length = 120
skip-string-normalization = true

[[tool.poetry.source]]
name = "mirrors"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true
secondary = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
