{{- range .Values.cronjob}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: tushare-integration-{{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  schedule: {{ .cron_expr }}
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          {{- with $.Values.affinity }}
          affinity:
                {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.nodeSelector }}
          nodeSelector:
                {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with $.Values.tolerations}}
          tolerations:
                {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
            - name: config
              configMap:
                name: tushare-integration-cronjob
                items:
                  - key: cronjob.yaml
                    path: jobs.yaml
          containers:
            - name: {{ .name }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
              args:
                - -c
                - "python main.py run job {{ .name }}"
              env:
                - name: 'TUSHARE_TOKEN'
                  value: '{{ $.Values.token }}'
                - name: 'DB_URI'
                  value: '{{ $.Values.db_uri }}'
                - name: 'DB_NAME'
                  value: '{{ $.Values.db_name }}'
                - name: 'DB_TYPE'
                  value: '{{ $.Values.db_type | default "clickhouse" }}'
              {{- range $.Values.env }}
                - name: '{{ .name }}'
                  value: '{{ .value }}'
              {{- end }}
              volumeMounts:
                - name: config
                  mountPath: /code/app/jobs.yaml
                  subPath: jobs.yaml
          restartPolicy: OnFailure
{{- end}}
